### ISSUE TITLE
Remove webpack

### ISSUE THREAD

**Issue by walaura** [walaura/pancakes-or-waffles#211]
- PHASE 1
- [x] make posts fetch their own css
- PHASE 2
- [x] make posts shadow dom
- [x] move css to [shadow root](https://developers.google.com/web/fundamentals/web-components/shadowdom#host)
- PHASE 3
- [x] abstract remote fetching+loading code
- [x] write custom local yaml+txt loader
- PHASE 4
- [x] actually remove webpack

Gosh imagine the dev load times

**Comment by noahleigh** [comment]
Is this a speed thing?

**Comment by walaura** [comment]
Chrome supports js modules locally so it saves all the compile time plus having webpack and babel as dependencies
